[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
ipocontract_addr='0xec49f014dc62e54be62307770c05a1bff078e49ac5ca902d716984a3fa9c4985'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
